@startuml
'Title'
title RESTful API Adapter - Component

'Use UML2 icons'
skinparam componentStyle uml2


'Components'
component "API Version Manager" as apimngr
component "API Differential Comparer" as compchecker
component "API Conflict Solver" as nodesolver
component "API Adaptation Mediator" as nodecoor


'Interfaces'
interface "HTTP" as http_nodecoor
interface "HTTP" as http_nodecloud
interface "HTTP" as http_apicloud



'Clouds'
cloud "Message Adapter Chain" as nodecloud {
    component "Adaptation Node 1...N" as apinodes
}
cloud "API Cloud" as apicloud {
    component "API 1...N" as apis
}

'Repositories'
database "API Repository" as apirep
database "Adaptation Flow Reposiory" as noderep


'Relations'
http_nodecoor -down- nodecoor
nodecoor -left-> noderep
nodecoor -down-( http_nodecloud
http_nodecloud -right- nodecloud
nodecloud -down-( http_apicloud
http_apicloud -right- apicloud
nodesolver -up-> noderep
nodesolver <-right- compchecker
compchecker -down-> apirep
apimngr -right-> apirep

'Notes'
note right of nodecoor
    Redirects all requests properly
    to the first link in the Message 
    Adapter Chain.
end note

note left of noderep
    Stores information on how messages 
    are delivered across the links in the 
    Message Adapter Chain
end note

note right of compchecker
    Compares two versions 
    of an API definition.
    Reports API diferences 
    as small differential.
end note

note left of nodesolver
    Renders API differentials
    into link navigations accross
    the Message Adapter Chain.
end note

note left of apimngr
    Stores API information
    for compatibility analysis.
end note

note right of nodecloud
    Holds all request adaptation nodes.
    Each node in the cloud takes care of
    adjusting each request for the next
    nodes located deeper into the cloud
    until the message is properly formatted
    to consume the latest version of the
    intended API.
end note

note right of apicloud
    Holds the latest version of the APIS
    for system client IoT devices.
end note
@enduml
