@startuml
'** Title **'
title Case Study - API Objects

'** Diagram Direction **'
'left to right direction'

'** Use UML2 icons **'
skinparam componentStyle uml2


'/////////// NODES ///////////'
'** Main **'
object "API Definition (OpenApi)" as apidef

'** API Description Nodes **'
object "OpenAPI" as api_openapi {
    version = "3.0.0"
}
object "Info" as api_info {
    title = "SHAS API"
    description = "Smart-Home Alarm System API"
    version = "1.0.0"
}
object "Servers" as api_servers
object "Paths" as api_paths

'** Server Nodes **'
object "Production" as server_prod {
    url = "https://shas.io/v1"
    description = "Production environment"
}
object "Staging" as server_stg {
    url = "http://staging-shas.io"
    description = "Staging environment"
}

'** Path **'
object "/fire_report" as path_firerep
object "/fire_report/{id}" as path_firerepid
object "/carbon_monoxide" as path_corep
object "/carbon_monoxide" as path_corepid

'** Verb **'
object "GET" as firerep_get
object "POST" as firerep_post
object "GET" as firerepid_get
object "GET" as corep_get
object "POST" as corep_post
object "GET" as corepid_get

'** Verb Path Params **'
object "Path Params" as firerepid_get_params
object "Path Params" as corepid_get_params

'** Path Params **'
object "Fire Report Id" as firerepid_get_params_id {
    in = "path"
    name = "id"
    type = "integer"
    required = "true"
}
object "Carbon Monoxide Report Id" as corepid_get_params_id {
    in = "path"
    name = "id"
    type = "integer"
    required = "true"
}

'** Request **'
object "Request" as firerep_post_req
object "Request" as corep_post_req

'** Request - Content **'
object "Content" as firerep_post_req_cont
object "Content" as corep_post_req_cont

'** Request - Content - Representation **'
object "Representation" as firerep_post_req_rep {
    representation = "application/json"
}
object "Representation" as corep_post_req_rep {
    representation = "application/json"
}

'** Request - Content - Schema **'
object "Schema" as firerep_post_req_schema
object "Schema" as corep_post_req_schema

'** Request - Content - Schema - Properties **'
object "Properties" as firerep_post_req_schema_prop {
    sensorID = integer
    sensorModelID = string
    measurement = integer
    measerureDate = integer
}
object "Properties" as corep_post_req_schema_prop {
    sensorID = integer
    sensorModelID = string
    measurement = integer
    measerureDate = integer
}

'** Response **'
object "Response" as firerep_get_resp
object "Response" as firerep_post_resp
object "Response" as firerepid_get_resp
object "Response" as corep_get_resp
object "Response" as corep_post_resp
object "Response" as corepid_get_resp

'** Response - Content **'
object "Content" as firerep_get_resp_cont
object "Content" as firerep_post_resp_cont
object "Content" as firerepid_get_resp_cont
object "Content" as corep_get_resp_cont
object "Content" as corep_post_resp_cont
object "Content" as corepid_get_resp_cont

'** Response - Content - Representation **'
object "Representation" as firerep_get_resp_rep {
    representation = "application/json"
}
object "Representation" as firerep_post_resp_rep {
    representation = "application/json"
}
object "Representation" as firerepid_get_resp_rep {
    representation = "application/json"
}
object "Representation" as corep_get_resp_rep {
    representation = "application/json"
}
object "Representation" as corep_post_resp_rep {
    representation = "application/json"
}
object "Representation" as corepid_get_resp_rep {
    representation = "application/json"
}

'** Response - Content - Schema **'
object "Schema" as firerep_get_resp_schema
object "Schema" as firerep_post_resp_schema
object "Schema" as firerepid_get_resp_schema
object "Schema" as corep_get_resp_schema
object "Schema" as corep_post_resp_schema
object "Schema" as corepid_get_resp_schema

'** Response - Content - Schema - Properties **'
object "Properties" as firerep_get_resp_schema_prop {
    id = integer
    sensorID = integet
    sensorModelID = string
    measurement = integer
    measerureDate = integer
    fireDptID = integer
    name = string
    eta = integer
}
object "Properties" as firerep_post_resp_schema_prop {
    sensorID = integet
    sensorModelID = string
    measurement = integer
    measerureDate = integer
}
object "Properties" as firerepid_get_resp_schema_prop {
    id = integer
    sensorID = integet
    sensorModelID = string
    measurement = integer
    measerureDate = integer
    fireDptID = integer
    name = string
    eta = integer
}
object "Properties" as corep_get_resp_schema_prop {
    id = integer
    sensorID = integet
    sensorModelID = string
    measurement = integer
    measerureDate = integer
    fireDptID = integer
    name = string
    eta = integer
}
object "Properties" as corep_post_resp_schema_prop {
    sensorID = integet
    sensorModelID = string
    measurement = integer
    measerureDate = integer
}
object "Properties" as corepid_get_resp_schema_prop {
    id = integer
    sensorID = integet
    sensorModelID = string
    measurement = integer
    measerureDate = integer
    fireDptID = integer
    name = string
    eta = integer
}

'/////////// RELATIONS ///////////'
'** API **'
apidef *-- api_openapi
apidef *-- api_info
apidef *-- api_servers
apidef *-- api_paths

'** Servers **'
api_servers *-- server_prod
api_servers *-- server_stg

'** Paths **'
api_paths *-- path_firerep
api_paths *-- path_firerepid
api_paths *-- path_corep
api_paths *-- path_corepid

'** Verbs **'
path_firerep *-- firerep_get
path_firerep *-- firerep_post
path_firerepid *-- firerepid_get
path_corep *-- corep_get
path_corep *-- corep_post
path_corepid *-- corepid_get

'** Verbs - Path Params **'
firerepid_get *-- firerepid_get_params
corepid_get *-- corepid_get_params

'** Verbs - Path Params - Ids **'
firerepid_get_params *-- firerepid_get_params_id
corepid_get_params *-- corepid_get_params_id

'** Requests **'
firerep_post *-- firerep_post_req
corep_post *-- corep_post_req

'** Requests - Content **'
firerep_post_req *-- firerep_post_req_cont
corep_post_req *-- corep_post_req_cont

'** Requests - Content - Representation **'
firerep_post_req_cont *-- firerep_post_req_rep
corep_post_req_cont *-- corep_post_req_rep

'** Requests - Content - Representation - Schema **'
firerep_post_req_rep *-- firerep_post_req_schema
corep_post_req_rep *-- corep_post_req_schema

'** Requests - Content - Representation - Properties **'
firerep_post_req_schema *-- firerep_post_req_schema_prop
corep_post_req_schema *-- corep_post_req_schema_prop

'** Responses **'
firerep_get *-- firerep_get_resp
firerep_post *-- firerep_post_resp
firerepid_get *-- firerepid_get_resp
corep_get *-- corep_get_resp
corep_post *-- corep_post_resp
corepid_get *-- corepid_get_resp

'** Responses - Content **'
firerep_get_resp *-- firerep_get_resp_cont
firerep_post_resp *-- firerep_post_resp_cont
firerepid_get_resp *-- firerepid_get_resp_cont
corep_get_resp *-- corep_get_resp_cont
corep_post_resp *-- corep_post_resp_cont
corepid_get_resp *-- corepid_get_resp_cont

'** Responses - Content - Representation **'
firerep_get_resp_cont *-- firerep_get_resp_rep
firerep_post_resp_cont *-- firerep_post_resp_rep
firerepid_get_resp_cont *-- firerepid_get_resp_rep
corep_get_resp_cont *-- corep_get_resp_rep
corep_post_resp_cont *-- corep_post_resp_rep
corepid_get_resp_cont *-- corepid_get_resp_rep

'** Responses - Content - Representation - Schema**'
firerep_get_resp_rep *-- firerep_get_resp_schema
firerep_post_resp_rep *-- firerep_post_resp_schema
firerepid_get_resp_rep *-- firerepid_get_resp_schema
corep_get_resp_rep *-- corep_get_resp_schema
corep_post_resp_rep *-- corep_post_resp_schema
corepid_get_resp_rep *-- corepid_get_resp_schema

'** Responses - Content - Representation - Properties**'
firerep_get_resp_schema *-- firerep_get_resp_schema_prop
firerep_post_resp_schema *-- firerep_post_resp_schema_prop
firerepid_get_resp_schema *-- firerepid_get_resp_schema_prop
corep_get_resp_schema *-- corep_get_resp_schema_prop
corep_post_resp_schema *-- corep_post_resp_schema_prop
corepid_get_resp_schema *-- corepid_get_resp_schema_prop
@enduml
