@startuml
title Traverse RC2 - TYPE CHANGE

rectangle LIST {
  storage "Welcome" as w1
  storage "List of Fire Reports" as lsfr
  rectangle "List" as ls
        
  w1 -right-> ls
  ls -right-> lsfr
}
note top of ls :Request to list fire reports

rectangle CREATE {
  storage "Welcome" as w2
  storage "Fire Report Created" as mkfr
  rectangle "Create" as mk

  w2 -right-> mk
  mk -right-> mkfr
}
note top of mk :Request to create a fire report
@enduml
